pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.homepage, name='homepage')
]

pet_adoption/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('pets/', include('pets.urls', namespace='pets')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('', include('pages.urls', namespace='pages'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/urls.py
from django.urls import path

from . import views

app_name = 'pets'

urlpatterns = [
    path('', views.get_pets, name='pets'),
    path('<int:pk>/', views.get_pet_detail, name='pet_detail')
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.get_posts, name='posts'),
    path('<int:pk>/', views.get_post_detail, name='post_detail'),
    path('category/<int:pk>/', views.get_category, name='category')
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.registration_view, name='register'),
    path('logout', views.logout_view, name='logout'),
    path('add-to-selected-pets/<int:pk>/', views.add_to_selected_pets_view,
         name='add_to_selected_pets'),
    path('delete-from-selected-pets/<int:pk>/',
         views.delete_from_selected_pets_view,
         name='delete_from_selected_pets'),
    path('selected-pets/', views.selected_pets_view, name='selected_pets'),
    path('adopt/', views.adoption_view, name='adoption'),
    path('history/', views.history_view, name='history')
]

pages/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Pet Adoption | Home</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static  'css/style.css'%}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm py-3 py-lg-0 px-3 px-lg-0">
        <a href="{% url 'pages:homepage' %}" class="navbar-brand ms-lg-5">
            <h1 class="m-0 text-uppercase text-dark">
                <i class="bi bi-house fs-1 text-primary me-3"></i>Pet Adoption
            </h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="{% url 'pages:homepage' %}" class="nav-item nav-link {% if request.path == '/' %}active{% endif %}">
                    Home
                </a>
                <a href="{% url 'pets:pets' %}" class="nav-item nav-link {% if request.path == '/pets/' %}active{% endif %}">
                    Pets
                </a>
                <a href="{% url 'posts:posts' %}" class="nav-item nav-link {% if request.path == '/posts/' %}active{% endif %}">
                    Posts
                </a>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:selected_pets' %}" class="nav-item nav-link {% if request.path == '/accounts/selected-pets/' %}active{% endif %}">
                        Selected Pets
                    </a>
                    <a href="{% url 'users:history' %}" class="nav-item nav-link {% if request.path == '/accounts/history/' %}active{% endif %}">
                        History
                    </a>
                    <a href="{% url 'users:logout' %}" class="nav-item nav-link me-5">
                        Log out
                    </a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="nav-item nav-link nav-contact bg-primary text-white px-5 ms-lg-5">
                        Sign in <i class="bi bi-arrow-right"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container-fluid bg-primary py-5 mb-5 hero-header" style="background: url('{{ banner.image.url }}') top right no-repeat; background-size: cover;">
        <div class="container py-5">
            <div class="row justify-content-start">
                <div class="col-lg-8 text-center text-lg-start">
                    <h1 class="display-1 text-uppercase text-dark mb-lg-4">{{ banner.title }}</h1>
                    <h1 class="text-uppercase text-white mb-lg-4">{{ banner.sub_title }}</h1>
                    <p class="fs-4 text-white mb-lg-4">{{ banner.description }}</p>
                    <div class="d-flex align-items-center justify-content-center justify-content-lg-start pt-5">
                        <button type="button" class="btn-play" data-bs-toggle="modal" data-src="{{ banner.video_link }}" data-bs-target="#videoModal">
                            <span></span>
                        </button>
                        <h5 class="font-weight-normal text-white m-0 ms-4 d-none d-sm-block">
                            Play Video
                        </h5>
                    </div>
                </div>
            </div>
        </div>
        <div id="about"></div>
    </div>

    <div class="modal fade" id="videoModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content rounded-0">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        Youtube Video
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="ratio ratio-16x9">
                        <iframe class="embed-responsive-item" src="{{ banner.video_link }}" id="video" allowfullscreen allowscriptaccess="always"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid py-5">
        <div class="container">
            <div class="row gx-5">
                <div class="col-lg-5 mb-5 mb-lg-0" style="min-height: 500px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100 rounded" src="{{ about_section.image.url }}" style="object-fit: cover;">
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="border-start border-5 border-primary ps-5 mb-5">
                        <h6 class="text-primary text-uppercase">
                            About Us
                        </h6>
                        <h1 class="display-5 text-uppercase mb-0">
                            {{ about_section.title }}
                        </h1>
                    </div>
                    <h5 class="text-body mb-4">
                        {{ about_section.description }}
                    </h5>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid py-5">
        <div class="container">
            <div class="border-start border-5 border-primary ps-5 mb-5" style="max-width: 600px;">
                <h6 class="text-primary text-uppercase">
                    Pets
                </h6>
                <h1 class="display-5 text-uppercase mb-0">
                    Our Pets Are Waiting For You
                </h1>
            </div>
            <div class="owl-carousel team-carousel position-relative" style="padding-right: 25px;">
                {% for pet in pets %}
                    <div class="team-item">
                        <div class="position-relative overflow-hidden">
                            <img class="img-fluid w-100" src="{{ pet.image.url }}" alt="{{ pet.name }}">
                        </div>
                        <div class="bg-light text-center d-flex flex-column p-3">
                            <a class="h5 bg-light" href="{% url 'pets:pet_detail' pk=pet.pk %}">
                                {{ pet.name }}
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="container-fluid py-5">
        <div class="container">
            <div class="border-start border-5 border-primary ps-5 mb-5" style="max-width: 600px;">
                <h6 class="text-primary text-uppercase">
                    Blog
                </h6>
                <h1 class="display-5 text-uppercase mb-0">
                    Latest Articles
                </h1>
            </div>
            <div class="row g-5">
                {% for post in posts %}
                    <div class="col-lg-6">
                        <div class="blog-item">
                            <div class="row g-0 bg-light overflow-hidden">
                                <div class="col-12 col-sm-5 h-100">
                                    <img class="img-fluid h-100" src="{{ post.image.url }}" style="object-fit: cover;">
                                </div>
                                <div class="col-12 col-sm-7 h-100 d-flex flex-column justify-content-center">
                                    <div class="p-4">
                                        <div class="d-flex mb-3">
                                            <small class="me-3">
                                                <i class="bi bi-bookmarks me-2"></i>{{ post.category.title }}
                                            </small>
                                            <small>
                                                <i class="bi bi-calendar-date me-2"></i>{{ post.created_at|date:"d.m.Y" }}, at {{ post.created_at|time:"H:i" }}
                                            </small>
                                        </div>
                                        <h5 class="text-uppercase mb-3">
                                            {{ post.title|truncatechars:64 }}
                                        </h5>
                                        <p>
                                            {{ post.description|truncatechars:128 }}
                                        </p>
                                        <a class="text-primary text-uppercase" href="{% url 'posts:post_detail' pk=post.pk %}">
                                            Read More<i class="bi bi-chevron-right"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="container-fluid bg-light mt-4 py-5">
        <div class="container pt-2">
            <div class="row g5 justify-content-center">
                <div class="col-lg-4 offset-1">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Get In Touch
                    </h5>
                    <p class="mb-2">
                        <i class="bi bi-geo-alt text-primary me-2"></i>Our office: Tashkent, Uzbekistan
                    </p>
                    <p class="mb-2">
                        <i class="bi bi-envelope-open text-primary me-2"></i>Email Us: info@example.com
                    </p>
                    <p class="mb-0">
                        <i class="bi bi-telephone text-primary me-2"></i>Call Us: +998(99)123-45-67
                    </p>
                </div>
                <div class="col-lg-4 offset-2">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Quick Links
                    </h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Home
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}#about">
                            <i class="bi bi-arrow-right text-primary me-2"></i>About Us
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}#about">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Our Services
                        </a>
                        <a class="text-body mb-2" href="{% url 'posts:posts' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Blog
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-dark text-white-50 py-4">
        <div class="container">
            <div class="row g-5">
                <div class="text-center">
                    <p class="mb-0">
                        This template was designed by <a class="text-white" href="https://htmlcodex.com">HTML Codex</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <a href="#" class="btn btn-primary py-3 fs-4 back-to-top">
        <i class="bi bi-arrow-up"></i>
    </a>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>