pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.homepage, name='homepage')
]

pet_adoption/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('pets/', include('pets.urls', namespace='pets')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('', include('pages.urls', namespace='pages'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/urls.py
from django.urls import path

from . import views

app_name = 'pets'

urlpatterns = [
    path('', views.get_pets, name='pets'),
    path('<int:pk>/', views.get_pet_detail, name='pet_detail')
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.get_posts, name='posts'),
    path('<int:pk>/', views.get_post_detail, name='post_detail'),
    path('category/<int:pk>/', views.get_category, name='category')
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.registration_view, name='register'),
    path('logout', views.logout_view, name='logout'),
    path('add-to-selected-pets/<int:pk>/', views.add_to_selected_pets_view,
         name='add_to_selected_pets'),
    path('delete-from-selected-pets/<int:pk>/',
         views.delete_from_selected_pets_view,
         name='delete_from_selected_pets'),
    path('selected-pets/', views.selected_pets_view, name='selected_pets'),
    path('adopt/', views.adoption_view, name='adoption'),
    path('history/', views.history_view, name='history')
]

users/models.py
from django.contrib.auth.models import User
from django.db import models

from pets.models import PetModel


class SelectedPetModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pet = models.ForeignKey(PetModel, on_delete=models.CASCADE)
    is_adopted = models.BooleanField(default=False)
    quantity = models.PositiveIntegerField()
    total_price = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}: {self.quantity} x {self.pet}'


class AdoptionModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=16)
    address = models.CharField(max_length=128)
    selected_pets = models.ManyToManyField(SelectedPetModel)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import AdoptionModel


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class AdoptionModelForm(forms.ModelForm):
    class Meta:
        model = AdoptionModel
        fields = ['name', 'email', 'phone_number', 'address']

users/views.py
from django.contrib import messages
from django.contrib.auth import logout, login
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

from pets.models import PetModel
from .forms import RegistrationForm, AdoptionModelForm
from .models import SelectedPetModel, AdoptionModel


def registration_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)

        if form.is_valid():
            username = form.clean_username()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password2')
            user = User.objects.create_user(username=username, email=email,
                                            password=password)

            user.save()
            login(request, user)

            return redirect('pages:homepage')

        context = {'form': form}
        return render(request, 'registration/registration.html', context)
    return render(request, 'registration/registration.html')


def logout_view(request):
    logout(request)

    return redirect('pages:homepage')


def add_to_selected_pets_view(request, pk):
    if request.method == 'POST':
        pet = PetModel.objects.get(id=pk)
        quantity = int(request.POST.get('quantity', 1))

        if pet.quantity >= quantity:
            total_price = pet.price * quantity

            SelectedPetModel.objects.create(user=request.user,
                                            pet=pet,
                                            quantity=quantity,
                                            total_price=total_price).save()

            return redirect('users:selected_pets')
        else:
            messages.error(request, 'Check available quantity!')
            return redirect('pets:pet_detail', pk=pet.id)


def delete_from_selected_pets_view(request, pk):
    pet = PetModel.objects.get(id=pk)
    SelectedPetModel.objects.filter(pet=pet).delete()

    return redirect('users:selected_pets')


def selected_pets_view(request):
    selected_pets = SelectedPetModel.objects.filter(user=request.user.id,
                                                    is_adopted=False)
    total = 0

    for pet in selected_pets:
        # final price for all selected pets
        total += pet.total_price

    context = {'selected_pets': selected_pets, 'total': total}

    return render(request, 'selected-pets.html', context)


def adoption_view(request):
    selected_pets = SelectedPetModel.objects.filter(user=request.user.id,
                                                    is_adopted=False)

    if request.method == 'POST':
        form = AdoptionModelForm(request.POST)

        if form.is_valid():
            adoption = form.save(commit=False)
            adoption.user = request.user
            adoption.save()
            adoption.selected_pets.set(selected_pets)

            for pet in selected_pets:
                pet.is_adopted = True
                # decrease the quantity of each pet being adopted in db
                pet.pet.quantity -= pet.quantity
                pet.save()
                pet.pet.save()

            return redirect('users:history')
        context = {'form': form}

        return render(request, 'adoption.html', context)

    total = 0

    for pet in selected_pets:
        # final price for all selected pets
        total += pet.total_price

    context = {'selected_pets': selected_pets, 'total': total}

    return render(request, 'adoption.html', context)


def history_view(request):
    adoptions = AdoptionModel.objects.filter(user=request.user)
    context = {'adoptions': adoptions}

    return render(request, 'history.html', context)

users/templates/adoption.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Pet Adoption | Adoption</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static  'css/style.css'%}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm py-3 py-lg-0 px-3 px-lg-0">
        <a href="{% url 'pages:homepage' %}" class="navbar-brand ms-lg-5">
            <h1 class="m-0 text-uppercase text-dark">
                <i class="bi bi-house fs-1 text-primary me-3"></i>Pet Adoption
            </h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="{% url 'pages:homepage' %}" class="nav-item nav-link {% if request.path == '/' %}active{% endif %}">
                    Home
                </a>
                <a href="{% url 'pets:pets' %}" class="nav-item nav-link {% if request.path == '/pets/' %}active{% endif %}">
                    Pets
                </a>
                <a href="{% url 'posts:posts' %}" class="nav-item nav-link {% if request.path == '/posts/' %}active{% endif %}">
                    Posts
                </a>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:selected_pets' %}" class="nav-item nav-link {% if request.path == '/accounts/selected-pets/' %}active{% endif %}">
                        Selected Pets
                    </a>
                    <a href="{% url 'users:history' %}" class="nav-item nav-link {% if request.path == '/accounts/history/' %}active{% endif %}">
                        History
                    </a>
                    <a href="{% url 'users:logout' %}" class="nav-item nav-link me-5">
                        Log out
                    </a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="nav-item nav-link nav-contact bg-primary text-white px-5 ms-lg-5">
                        Sign in <i class="bi bi-arrow-right"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container py-5">
        <div class="border-start border-5 border-primary ps-5 mb-5" style="max-width: 600px;">
            <h1 class="display-5 text-uppercase mb-0">Enter your details, </h1>
            <h1 class="display-5 mb-0">{{ request.user.username }}</h1>
        </div>
        <div class="row g-5">
            <div class="col-lg-8">
                <div class="mb-3">
                    <form method="post">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-12">
                                <input type="text" class="form-control bg-light border-0 px-4" name="name" placeholder="Your Full Name" style="height: 55px;" required>
                            </div>
                            <div class="col-6">
                                <input type="email" class="form-control bg-light border-0 px-4" name="email" placeholder="Your Email" value="{{ request.user.email }}" style="height: 55px;" required>
                                {% if form.email.errors %}
                                    <p class="text-danger">
                                        {% for error in form.email.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </p>
                                {% endif %}
                            </div>
                            <div class="col-6">
                                <input type="tel" class="form-control bg-light border-0 px-4" name="phone_number" placeholder="Your Phone Number (+998xxxxxxxxx)" value="+998" pattern="^\+998\d{9}$" style="height: 55px;" required>
                                {% if form.phone_number.errors %}
                                    <p class="text-danger">
                                        {% for error in form.phone_number.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </p>
                                {% endif %}
                            </div>
                            <div class="col-12">
                                <input type="text" class="form-control bg-light border-0 px-4" name="address" placeholder="Your Address" style="height: 55px;" required>
                            </div>
                            <div class="col-3">
                                <button class="btn btn-primary w-100 py-3" type="submit">
                                    Done
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="mb-5">
                    <h3 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Pets You Selected
                    </h3>
                    {% for pet in selected_pets %}
                        <div class="d-flex overflow-hidden mb-3">
                            <img class="img-fluid" src="{{ pet.pet.image.url }}" style="width: 100px; height: 100px; object-fit: cover;" alt="{{ pet.pet.name }}">
                            <a href="{% url 'pets:pet_detail' pk=pet.pet.pk %}" class="h5 d-flex align-items-center bg-light px-3 mb-0" style="width: 100%">
                                {{ pet.pet.name }}
                            </a>
                        </div>
                    {% empty %}
                        <p>
                            No pets found
                        </p>
                    {% endfor %}
                    <h2 class="d-inline display-6">
                        Total: ${{ total }}
                    </h2>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-light mt-4 py-5">
        <div class="container pt-2">
            <div class="row g5 justify-content-center">
                <div class="col-lg-4 offset-1">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Get In Touch
                    </h5>
                    <p class="mb-2">
                        <i class="bi bi-geo-alt text-primary me-2"></i>Our office: Tashkent, Uzbekistan
                    </p>
                    <p class="mb-2">
                        <i class="bi bi-envelope-open text-primary me-2"></i>Email Us: info@example.com
                    </p>
                    <p class="mb-0">
                        <i class="bi bi-telephone text-primary me-2"></i>Call Us: +998(99)123-45-67
                    </p>
                </div>
                <div class="col-lg-4 offset-2">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Quick Links
                    </h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Home
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>About Us
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Our Services
                        </a>
                        <a class="text-body mb-2" href="{% url 'posts:posts' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Blog
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-dark text-white-50 py-4">
        <div class="container">
            <div class="row g-5">
                <div class="text-center">
                    <p class="mb-0">
                        This template was designed by <a class="text-white" href="https://htmlcodex.com">HTML Codex</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <a href="#" class="btn btn-primary py-3 fs-4 back-to-top">
        <i class="bi bi-arrow-up"></i>
    </a>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

users/templates/selected-pets.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Pet Adoption | Selected Pets</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static  'css/style.css'%}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm py-3 py-lg-0 px-3 px-lg-0">
        <a href="{% url 'pages:homepage' %}" class="navbar-brand ms-lg-5">
            <h1 class="m-0 text-uppercase text-dark">
                <i class="bi bi-house fs-1 text-primary me-3"></i>Pet Adoption
            </h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="{% url 'pages:homepage' %}" class="nav-item nav-link {% if request.path == '/' %}active{% endif %}">
                    Home
                </a>
                <a href="{% url 'pets:pets' %}" class="nav-item nav-link {% if request.path == '/pets/' %}active{% endif %}">
                    Pets
                </a>
                <a href="{% url 'posts:posts' %}" class="nav-item nav-link {% if request.path == '/posts/' %}active{% endif %}">
                    Posts
                </a>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:selected_pets' %}" class="nav-item nav-link {% if request.path == '/accounts/selected-pets/' %}active{% endif %}">
                        Selected Pets
                    </a>
                    <a href="{% url 'users:history' %}" class="nav-item nav-link {% if request.path == '/accounts/history/' %}active{% endif %}">
                        History
                    </a>
                    <a href="{% url 'users:logout' %}" class="nav-item nav-link me-5">
                        Log out
                    </a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="nav-item nav-link nav-contact bg-primary text-white px-5 ms-lg-5">
                        Sign in <i class="bi bi-arrow-right"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container-fluid py-5">
        <div class="container">
            <div class="border-start border-5 border-primary ps-5 mb-5" style="max-width: 600px;">
                <h1 class="display-5 text-uppercase mb-0">
                    My Selected Pets
                </h1>
            </div>
            <div class="row g-5">
                <div class="col-lg-12">
                    <table class="table table-bordered text-center mb-1">
                        <thead>
                        <tr>
                            <th scope="col">
                                #
                            </th>
                            <th scope="col">
                                Image
                            </th>
                            <th scope="col">
                                Name
                            </th>
                            <th scope="col">
                                Quantity
                            </th>
                            <th scope="col">
                                Price
                            </th>
                            <th scope="col">
                                Keep?
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for pet in selected_pets %}
                            <tr>
                                <td>
                                    <strong>{{ forloop.counter }}</strong>
                                </td>
                                <td>
                                    <img src="{{ pet.pet.image.url }}" width="200" height="150" alt="{{ pet.pet.name }}">
                                </td>
                                <td>
                                    <a href="{% url 'pets:pet_detail' pk=pet.pet.pk %}">{{ pet.pet.name }}</a>
                                </td>
                                <td>
                                   <p>{{ pet.quantity }}</p>
                                </td>
                                <td>
                                    ${{ pet.total_price }}
                                </td>
                                <td>
                                    <a href="{% url 'users:delete_from_selected_pets' pk=pet.pet.pk %}" class="btn btn-primary py-3">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <h2 class="d-inline display-6">
                        Total: ${{ total }}
                    </h2>
                    <a href="{% if selected_pets.count == 0 %}{% url 'users:selected_pets' %}{% else %}{% url 'users:adoption' %}{% endif %}" class="btn btn-primary float-end py-3" style="white-space: nowrap;">
                        <i class="bi bi-hand-thumbs-up me-2"></i> Adopt Now
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-light mt-4 py-5">
        <div class="container pt-2">
            <div class="row g5 justify-content-center">
                <div class="col-lg-4 offset-1">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Get In Touch
                    </h5>
                    <p class="mb-2">
                        <i class="bi bi-geo-alt text-primary me-2"></i>Our office: Tashkent, Uzbekistan
                    </p>
                    <p class="mb-2">
                        <i class="bi bi-envelope-open text-primary me-2"></i>Email Us: info@example.com
                    </p>
                    <p class="mb-0">
                        <i class="bi bi-telephone text-primary me-2"></i>Call Us: +998(99)123-45-67
                    </p>
                </div>
                <div class="col-lg-4 offset-2">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Quick Links
                    </h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Home
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>About Us
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Our Services
                        </a>
                        <a class="text-body mb-2" href="{% url 'posts:posts' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Blog
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-dark text-white-50 py-4">
        <div class="container">
            <div class="row g-5">
                <div class="text-center">
                    <p class="mb-0">
                        This template was designed by <a class="text-white" href="https://htmlcodex.com">HTML Codex</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <a href="#" class="btn btn-primary py-3 fs-4 back-to-top">
        <i class="bi bi-arrow-up"></i>
    </a>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>