pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.homepage, name='homepage')
]

pet_adoption/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('pets/', include('pets.urls', namespace='pets')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('', include('pages.urls', namespace='pages'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/urls.py
from django.urls import path

from . import views

app_name = 'pets'

urlpatterns = [
    path('', views.get_pets, name='pets'),
    path('<int:pk>/', views.get_pet_detail, name='pet_detail')
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.get_posts, name='posts'),
    path('<int:pk>/', views.get_post_detail, name='post_detail'),
    path('category/<int:pk>/', views.get_category, name='category')
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.registration_view, name='register'),
    path('logout', views.logout_view, name='logout'),
    path('add-to-selected-pets/<int:pk>/', views.add_to_selected_pets_view,
         name='add_to_selected_pets'),
    path('delete-from-selected-pets/<int:pk>/',
         views.delete_from_selected_pets_view,
         name='delete_from_selected_pets'),
    path('selected-pets/', views.selected_pets_view, name='selected_pets'),
    path('adopt/', views.adoption_view, name='adoption'),
    path('history/', views.history_view, name='history')
]

posts/models.py
from django.db import models


class PostCategoryModel(models.Model):
    title = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class PostModel(models.Model):
    image = models.ImageField(upload_to='posts')
    title = models.CharField(max_length=64)
    description = models.TextField()
    category = models.ForeignKey(PostCategoryModel, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from .models import PostModel, PostCategoryModel


def get_posts(request):
    search_query = request.GET.get('search', '')

    # search by title or description
    if search_query:
        posts = (PostModel.objects.filter(
            title__icontains=search_query
        ).order_by('-created_at') | PostModel.objects.filter(
            description__icontains=search_query).order_by('-created_at'))
    else:
        posts = PostModel.objects.all().order_by('-created_at')

    recent_posts = PostModel.objects.order_by('-created_at')[:4]
    categories = PostCategoryModel.objects.all()

    # pagination configuration, showing 8 posts on one page
    paginator = Paginator(posts, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'recent_posts': recent_posts, 'categories': categories,
               'page_obj': page_obj}

    return render(request, 'posts.html', context)


def get_post_detail(request, pk):
    post = PostModel.objects.get(id=pk)
    # get related by category posts except itself
    related_posts = PostModel.objects.filter(
        category=post.category
    ).exclude(id=post.pk).order_by('-created_at')
    context = {'post': post, 'related_posts': related_posts}

    return render(request, 'post-detail.html', context)


def get_category(request, pk):
    category = PostCategoryModel.objects.get(id=pk)
    posts = PostModel.objects.filter(category=category).order_by('-created_at')

    # pagination configuration, showing 8 filtered by category posts per page
    paginator = Paginator(posts, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'category': category, 'page_obj': page_obj}

    return render(request, 'categories.html', context)

posts/templates/categories.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Pet Adoption | {{ category.title }}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static  'css/style.css'%}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm py-3 py-lg-0 px-3 px-lg-0">
        <a href="{% url 'pages:homepage' %}" class="navbar-brand ms-lg-5">
            <h1 class="m-0 text-uppercase text-dark">
                <i class="bi bi-house fs-1 text-primary me-3"></i>Pet Adoption
            </h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="{% url 'pages:homepage' %}" class="nav-item nav-link {% if request.path == '/' %}active{% endif %}">
                    Home
                </a>
                <a href="{% url 'pets:pets' %}" class="nav-item nav-link {% if request.path == '/pets/' %}active{% endif %}">
                    Pets
                </a>
                <a href="{% url 'posts:posts' %}" class="nav-item nav-link {% if request.path == '/posts/' %}active{% endif %}">
                    Posts
                </a>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:selected_pets' %}" class="nav-item nav-link {% if request.path == '/accounts/selected-pets/' %}active{% endif %}">
                        Selected Pets
                    </a>
                    <a href="{% url 'users:history' %}" class="nav-item nav-link {% if request.path == '/accounts/history/' %}active{% endif %}">
                        History
                    </a>
                    <a href="{% url 'users:logout' %}" class="nav-item nav-link me-5">
                        Log out
                    </a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="nav-item nav-link nav-contact bg-primary text-white px-5 ms-lg-5">
                        Sign in <i class="bi bi-arrow-right"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container py-5">
        <div class="row g-5">
            <div class="border-start border-5 border-primary ps-5 mb-5">
                <h1 class="display-5 text-uppercase mb-0">
                    News in category "{{ category.title }}"
                </h1>
            </div>
            {% for post in page_obj %}
                <div class="col-lg-6">
                    <div class="blog-item mb-5">
                        <div class="row g-0 bg-light overflow-hidden">
                            <div class="col-12 col-sm-5 h-100">
                                <img class="img-fluid h-100" src="{{ post.image.url }}" style="object-fit: cover;">
                            </div>
                            <div class="col-12 col-sm-7 h-100 d-flex flex-column justify-content-center">
                                <div class="p-4">
                                    <div class="d-flex mb-3">
                                        <small class="me-3">
                                            <i class="bi bi-bookmarks me-2"></i>{{ post.category.title }}
                                        </small>
                                        <small>
                                            <i class="bi bi-calendar-date me-2"></i>{{ post.created_at|date:"d.m.Y" }}, at {{ post.created_at|time:"H:i" }}
                                        </small>
                                    </div>
                                    <h5 class="text-uppercase mb-3">
                                        {{ post.title|truncatechars:64 }}
                                    </h5>
                                    <p>
                                        {{ post.description|truncatechars:128 }}
                                    </p>
                                    <a class="text-primary text-uppercase" href="{% url 'posts:post_detail' pk=post.pk %}">
                                        Read More<i class="bi bi-chevron-right"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <p>
                    No posts
                </p>
            {% endfor %}

            {% if page_obj %}
                <div class="col-12">
                    <nav aria-label="Page navigation">
                        <ul class="pagination pagination-lg m-0">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link rounded-0" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                        <span aria-hidden="true">
                                            <i class="bi bi-arrow-left"></i>
                                        </span>
                                    </a>
                                </li>
                            {% endif %}
                            <li class="page-item active">
                                <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                            </li>
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link rounded-0" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">
                                            <i class="bi bi-arrow-right"></i>
                                        </span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            {% else %}
            {% endif %}
        </div>
    </div>

    <div class="container-fluid bg-light mt-4 py-5">
        <div class="container pt-2">
            <div class="row g5 justify-content-center">
                <div class="col-lg-4 offset-1">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Get In Touch
                    </h5>
                    <p class="mb-2">
                        <i class="bi bi-geo-alt text-primary me-2"></i>Our office: Tashkent, Uzbekistan
                    </p>
                    <p class="mb-2">
                        <i class="bi bi-envelope-open text-primary me-2"></i>Email Us: info@example.com
                    </p>
                    <p class="mb-0">
                        <i class="bi bi-telephone text-primary me-2"></i>Call Us: +998(99)123-45-67
                    </p>
                </div>
                <div class="col-lg-4 offset-2">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Quick Links
                    </h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Home
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>About Us
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Our Services
                        </a>
                        <a class="text-body mb-2" href="{% url 'posts:posts' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Blog
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-dark text-white-50 py-4">
        <div class="container">
            <div class="row g-5">
                <div class="text-center">
                    <p class="mb-0">
                        This template was designed by <a class="text-white" href="https://htmlcodex.com">HTML Codex</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <a href="#" class="btn btn-primary py-3 fs-4 back-to-top">
        <i class="bi bi-arrow-up"></i>
    </a>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

posts/templates/posts.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Pet Adoption | Posts</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static  'css/style.css'%}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm py-3 py-lg-0 px-3 px-lg-0">
        <a href="{% url 'pages:homepage' %}" class="navbar-brand ms-lg-5">
            <h1 class="m-0 text-uppercase text-dark">
                <i class="bi bi-house fs-1 text-primary me-3"></i>Pet Adoption
            </h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="{% url 'pages:homepage' %}" class="nav-item nav-link {% if request.path == '/' %}active{% endif %}">
                    Home
                </a>
                <a href="{% url 'pets:pets' %}" class="nav-item nav-link {% if request.path == '/pets/' %}active{% endif %}">
                    Pets
                </a>
                <a href="{% url 'posts:posts' %}" class="nav-item nav-link {% if request.path == '/posts/' %}active{% endif %}">
                    Posts
                </a>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:selected_pets' %}" class="nav-item nav-link {% if request.path == '/accounts/selected-pets/' %}active{% endif %}">
                        Selected Pets
                    </a>
                    <a href="{% url 'users:history' %}" class="nav-item nav-link {% if request.path == '/accounts/history/' %}active{% endif %}">
                        History
                    </a>
                    <a href="{% url 'users:logout' %}" class="nav-item nav-link me-5">
                        Log out
                    </a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="nav-item nav-link nav-contact bg-primary text-white px-5 ms-lg-5">
                        Sign in <i class="bi bi-arrow-right"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-8">
                {% for post in page_obj %}
                    <div class="blog-item mb-5">
                        <div class="row g-0 bg-light overflow-hidden">
                            <div class="col-12 col-sm-5 h-100">
                                <img class="img-fluid h-100" src="{{ post.image.url }}" style="object-fit: cover;">
                            </div>
                            <div class="col-12 col-sm-7 h-100 d-flex flex-column justify-content-center">
                                <div class="p-4">
                                    <div class="d-flex mb-3">
                                        <small class="me-3">
                                            <i class="bi bi-bookmarks me-2"></i>{{ post.category.title }}
                                        </small>
                                        <small>
                                            <i class="bi bi-calendar-date me-2"></i>{{ post.created_at|date:"d.m.Y" }}, at {{ post.created_at|time:"H:i" }}
                                        </small>
                                    </div>
                                    <h5 class="text-uppercase mb-3">
                                        {{ post.title|truncatechars:64 }}
                                    </h5>
                                    <p>
                                        {{ post.description|truncatechars:128 }}
                                    </p>
                                    <a class="text-primary text-uppercase" href="{% url 'posts:post_detail' pk=post.pk %}">
                                        Read More<i class="bi bi-chevron-right"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <p>
                        No posts found
                    </p>
                {% endfor %}

                {% if page_obj %}
                    <div class="col-12">
                        <nav aria-label="Page navigation">
                            <ul class="pagination pagination-lg m-0">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link rounded-0" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                            <span aria-hidden="true"><i class="bi bi-arrow-left"></i></span>
                                        </a>
                                    </li>
                                {% endif %}
                                <li class="page-item active">
                                    <a class="page-link" href="?page={{ page_obj.number }}">
                                        {{ page_obj.number }}
                                    </a>
                                </li>
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link rounded-0" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                            <span aria-hidden="true"><i class="bi bi-arrow-right"></i></span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                {% else %}
                {% endif %}
            </div>

            <div class="col-lg-4">
                <div class="mb-5">
                    <div class="input-group">
                        <form method="GET" class="d-flex">
                            <input type="text" class="form-control p-3" name="search" placeholder="Search...">
                            <button class="btn btn-primary px-4" type="submit">
                                <i class="bi bi-search"></i>
                            </button>
                        </form>
                    </div>
                </div>

                <div class="mb-5">
                    <h3 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Categories
                    </h3>
                    <div class="d-flex flex-column justify-content-start">
                        {% for category in categories %}
                            <a class="h5 bg-light py-2 px-3 mb-2" href="{% url 'posts:category' pk=category.pk %}">
                                <i class="bi bi-arrow-right me-2"></i>{{ category.title }}
                            </a>
                        {% empty %}
                            <p>
                                No categories found
                            </p>
                        {% endfor %}
                    </div>
                </div>

                <div class="mb-5">
                    <h3 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Recent Posts
                    </h3>
                    {% for post in recent_posts %}
                        <div class="d-flex overflow-hidden mb-3">
                            <img class="img-fluid" src="{{ post.image.url }}" style="width: 100px; height: 100px; object-fit: cover;" alt="{{ post.title }}">
                            <a href="{% url 'posts:post_detail' pk=post.pk %}" class="h5 d-flex align-items-center bg-light px-3 mb-0">
                                {{ post.title }}
                            </a>
                        </div>
                    {% empty %}
                        <p>
                            No posts found
                        </p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-light mt-4 py-5">
        <div class="container pt-2">
            <div class="row g5 justify-content-center">
                <div class="col-lg-4 offset-1">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Get In Touch
                    </h5>
                    <p class="mb-2">
                        <i class="bi bi-geo-alt text-primary me-2"></i>Our office: Tashkent, Uzbekistan
                    </p>
                    <p class="mb-2">
                        <i class="bi bi-envelope-open text-primary me-2"></i>Email Us: info@example.com
                    </p>
                    <p class="mb-0">
                        <i class="bi bi-telephone text-primary me-2"></i>Call Us: +998(99)123-45-67
                    </p>
                </div>
                <div class="col-lg-4 offset-2">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Quick Links
                    </h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Home
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>About Us
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Our Services
                        </a>
                        <a class="text-body mb-2" href="{% url 'posts:posts' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Blog
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-dark text-white-50 py-4">
        <div class="container">
            <div class="row g-5">
                <div class="text-center">
                    <p class="mb-0">
                        This template was designed by <a class="text-white" href="https://htmlcodex.com">HTML Codex</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <a href="#" class="btn btn-primary py-3 fs-4 back-to-top">
        <i class="bi bi-arrow-up"></i>
    </a>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>