pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.homepage, name='homepage')
]

pet_adoption/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('pets/', include('pets.urls', namespace='pets')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('', include('pages.urls', namespace='pages'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/urls.py
from django.urls import path

from . import views

app_name = 'pets'

urlpatterns = [
    path('', views.get_pets, name='pets'),
    path('<int:pk>/', views.get_pet_detail, name='pet_detail')
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.get_posts, name='posts'),
    path('<int:pk>/', views.get_post_detail, name='post_detail'),
    path('category/<int:pk>/', views.get_category, name='category')
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.registration_view, name='register'),
    path('logout', views.logout_view, name='logout'),
    path('add-to-selected-pets/<int:pk>/', views.add_to_selected_pets_view,
         name='add_to_selected_pets'),
    path('delete-from-selected-pets/<int:pk>/',
         views.delete_from_selected_pets_view,
         name='delete_from_selected_pets'),
    path('selected-pets/', views.selected_pets_view, name='selected_pets'),
    path('adopt/', views.adoption_view, name='adoption'),
    path('history/', views.history_view, name='history')
]

pets/models.py
from django.db import models


class PetTypeModel(models.Model):
    type = models.CharField(max_length=16)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.type


class PetBreedModel(models.Model):
    breed = models.CharField(max_length=64)
    type = models.ForeignKey(PetTypeModel, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.type}: {self.breed}'


class PetSizeModel(models.Model):
    SIZE_CHOICES = [
        ('Small', 'Small'),
        ('Medium', 'Medium'),
        ('Large', 'Large'),
        ('Extra Large', 'Extra Large'),
    ]
    size = models.CharField(max_length=16, choices=SIZE_CHOICES)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description


class PetColorModel(models.Model):
    color = models.CharField(max_length=16)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.color


class PetModel(models.Model):
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female')
    ]
    image = models.ImageField(upload_to='pets')
    name = models.CharField(max_length=16)
    type = models.ForeignKey(PetTypeModel, on_delete=models.CASCADE)
    breed = models.ForeignKey(PetBreedModel, on_delete=models.CASCADE)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    size = models.ForeignKey(PetSizeModel, on_delete=models.CASCADE)
    age = models.PositiveIntegerField()
    color = models.ForeignKey(PetColorModel, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.FloatField()
    quantity = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.type}: {self.name}'

pets/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from users.models import SelectedPetModel
from .models import (PetModel, PetTypeModel, PetBreedModel, PetSizeModel,
                     PetColorModel)


def get_pets(request):
    search_query = request.GET.get('search', '')
    type_query = request.GET.get('type', '')
    breed_query = request.GET.get('breed', '')
    size_query = request.GET.get('size', '')
    color_query = request.GET.get('color', '')
    pets = PetModel.objects.filter(quantity__gt=0)

    # search by exactly one of the following criteria
    if search_query:
        pets = pets.filter(
            type__type__icontains=search_query
        ) | pets.filter(
            breed__breed__icontains=search_query)
    elif type_query:
        pets = pets.filter(type=type_query)
    elif breed_query:
        pets = pets.filter(breed=breed_query)
    elif size_query:
        pets = pets.filter(size=size_query)
    elif color_query:
        pets = pets.filter(color=color_query)

    types = PetTypeModel.objects.all()
    breeds = PetBreedModel.objects.all()
    sizes = PetSizeModel.objects.all()
    colors = PetColorModel.objects.all()

    # pagination configuration, showing 15 pets on one page
    paginator = Paginator(pets, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'types': types,
               'breeds': breeds,
               'sizes': sizes,
               'colors': colors,
               'page_obj': page_obj}

    return render(request, 'pets.html', context)


def get_pet_detail(request, pk):
    pet = PetModel.objects.get(id=pk)
    related_pets = PetModel.objects.filter(type=pet.type).exclude(id=pet.pk)
    # check whether user added the pet to 'selected pets'
    is_in_selected_pets = SelectedPetModel.objects.filter(
        user=request.user,
        pet=pet,
        is_adopted=False,
        quantity__gte=1).exists() if request.user.is_authenticated else False

    context = {'pet': pet,
               'related_pets': related_pets,
               'is_in_selected_pets': is_in_selected_pets}

    return render(request, 'pet-detail.html', context)

pets/templates/pet-detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Pet Adoption | {{ pet.name }}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static  'css/style.css'%}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm py-3 py-lg-0 px-3 px-lg-0">
        <a href="{% url 'pages:homepage' %}" class="navbar-brand ms-lg-5">
            <h1 class="m-0 text-uppercase text-dark">
                <i class="bi bi-house fs-1 text-primary me-3"></i>Pet Adoption
            </h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="{% url 'pages:homepage' %}" class="nav-item nav-link {% if request.path == '/' %}active{% endif %}">
                    Home
                </a>
                <a href="{% url 'pets:pets' %}" class="nav-item nav-link {% if request.path == '/pets/' %}active{% endif %}">
                    Pets
                </a>
                <a href="{% url 'posts:posts' %}" class="nav-item nav-link {% if request.path == '/posts/' %}active{% endif %}">
                    Posts
                </a>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:selected_pets' %}" class="nav-item nav-link {% if request.path == '/accounts/selected-pets/' %}active{% endif %}">
                        Selected Pets
                    </a>
                    <a href="{% url 'users:history' %}" class="nav-item nav-link {% if request.path == '/accounts/history/' %}active{% endif %}">
                        History
                    </a>
                    <a href="{% url 'users:logout' %}" class="nav-item nav-link me-5">
                        Log out
                    </a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="nav-item nav-link nav-contact bg-primary text-white px-5 ms-lg-5">
                        Sign in <i class="bi bi-arrow-right"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-9">
                <div class="mb-3">
                    <img class="img-fluid w-100 rounded mb-5" src="{{ pet.image.url }}" alt="{{ pet.name }}">
                    <h1 class="text-uppercase mb-4">
                        {{ pet.name }}
                    </h1>
                    <table class="table table-bordered table-striped table-hover mb-5">
                        <thead>
                        <tr>
                            <th scope="col">
                                Characteristics
                            </th>
                            <th scope="col">
                                Details
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <strong>Type:</strong>
                            </td>
                            <td>
                                {{ pet.type.type }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>Breed:</strong>
                            </td>
                            <td>
                                {{ pet.breed.breed }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>Gender:</strong>
                            </td>
                            <td>
                                {{ pet.gender }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>Size:</strong>
                            </td>
                            <td>
                                {{ pet.size.size }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>Age:</strong>
                            </td>
                            <td>
                                {{ pet.age }} year(s)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>Color:</strong>
                            </td>
                            <td>
                                {{ pet.color.color }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>Price per 1 pet:</strong>
                            </td>
                            <td>
                                ${{ pet.price }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>Quantity Available:</strong>
                            </td>
                            <td>
                                {{ pet.quantity }}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <h3 class="text-uppercase mb-3">
                        Description
                    </h3>
                    <p>
                        {{ pet.description }}
                    </p>

                    {% if user.is_authenticated %}
                        <div class="d-flex align-items-center mb-4">
                            {% if not is_in_selected_pets %}
                                <form action="{% url 'users:add_to_selected_pets' pk=pet.pk %}" method="post" class="d-flex align-items-center">
                                    {% csrf_token %}
                                    <div class="d-flex align-items-center">
                                        <input class="form-control bg-light border-0 py-3 me-2" type="number" min="1" name="quantity" value="1" placeholder="Quantity" style="max-width: 120px;">
                                        <button type="submit" class="btn btn-outline-primary py-3">
                                            Adopt
                                        </button>
                                    </div>
                                </form>
                                {% if messages %}
                                    {% for message in messages %}
                                        <h4 class="mx-3">
                                            {{ message }}
                                        </h4>
                                    {% endfor %}
                                {% endif %}
                            {% else %}
                                <p>
                                    This pet is already in 'SELECTED PETS' section
                                </p>
                            {% endif %}
                        </div>
                    {% else %}
                        <p>
                            Sign in to your account to adopt pets
                        </p>
                    {% endif %}
                </div>
            </div>

            <div class="col-lg-3">
                <div class="mb-5">
                    <h3 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Related Pets
                    </h3>
                    {% for pet in related_pets %}
                        <div class="d-flex overflow-hidden mb-3">
                            <img class="img-fluid" src="{{ pet.image.url }}" style="width: 100px; height: 100px; object-fit: cover;" alt="{{ pet.name }}">
                            <a href="{% url 'pets:pet_detail' pk=pet.pk %}" class="h5 d-flex align-items-center bg-light px-3 mb-0" style="width: 100%">
                                {{ pet.name }}
                            </a>
                        </div>
                    {% empty %}
                        <p>
                            No pets found
                        </p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-light mt-4 py-5">
        <div class="container pt-2">
            <div class="row g5 justify-content-center">
                <div class="col-lg-4 offset-1">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Get In Touch
                    </h5>
                    <p class="mb-2"><i class="bi bi-geo-alt text-primary me-2"></i>
                        Our office: Tashkent, Uzbekistan
                    </p>
                    <p class="mb-2"><i class="bi bi-envelope-open text-primary me-2"></i>
                        Email Us: info@example.com
                    </p>
                    <p class="mb-0"><i class="bi bi-telephone text-primary me-2"></i>
                        Call Us: +998(99)123-45-67
                    </p>
                </div>
                <div class="col-lg-4 offset-2">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Quick Links
                    </h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Home
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>About Us
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Our Services
                        </a>
                        <a class="text-body mb-2" href="{% url 'posts:posts' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Blog
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-dark text-white-50 py-4">
        <div class="container">
            <div class="row g-5">
                <div class="text-center">
                    <p class="mb-0">
                        This template was designed by <a class="text-white" href="https://htmlcodex.com">HTML Codex</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <a href="#" class="btn btn-primary py-3 fs-4 back-to-top">
        <i class="bi bi-arrow-up"></i>
    </a>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

pets/templates/pets.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Pet Adoption | Pets</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static  'css/style.css'%}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm py-3 py-lg-0 px-3 px-lg-0">
        <a href="{% url 'pages:homepage' %}" class="navbar-brand ms-lg-5">
            <h1 class="m-0 text-uppercase text-dark">
                <i class="bi bi-house fs-1 text-primary me-3"></i>Pet Adoption
            </h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="{% url 'pages:homepage' %}" class="nav-item nav-link {% if request.path == '/' %}active{% endif %}">
                    Home
                </a>
                <a href="{% url 'pets:pets' %}" class="nav-item nav-link {% if request.path == '/pets/' %}active{% endif %}">
                    Pets
                </a>
                <a href="{% url 'posts:posts' %}" class="nav-item nav-link {% if request.path == '/posts/' %}active{% endif %}">
                    Posts
                </a>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:selected_pets' %}" class="nav-item nav-link {% if request.path == '/accounts/selected-pets/' %}active{% endif %}">
                        Selected Pets
                    </a>
                    <a href="{% url 'users:history' %}" class="nav-item nav-link {% if request.path == '/accounts/history/' %}active{% endif %}">
                        History
                    </a>
                    <a href="{% url 'users:logout' %}" class="nav-item nav-link me-5">
                        Log out
                    </a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="nav-item nav-link nav-contact bg-primary text-white px-5 ms-lg-5">
                        Sign in <i class="bi bi-arrow-right"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container-fluid py-5">
        <div class="container">
            <div class="border-start border-5 border-primary ps-5 mb-5" style="max-width: 600px;">
                <h1 class="display-5 text-uppercase mb-0">
                    Pets
                </h1>
            </div>
            <div class="row g-5">
                <div class="col-lg-3">
                    <div class="mb-5">
                        <div class="input-group">
                            <form method="get" class="d-flex">
                                <input type="text" class="form-control p-3" name="search" placeholder="Search...">
                                <button class="btn btn-primary px-4" type="submit">
                                    <i class="bi bi-search"></i>
                                </button>
                            </form>
                        </div>
                    </div>

                    <div class="mb-5">
                        <h3 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                            Types
                        </h3>
                        <div class="d-flex flex-column justify-content-start">
                            {% for type in types %}
                                <a class="h5 bg-light py-2 px-3 mb-2" href="?type={{ type.id }}">
                                    <i class="bi bi-arrow-right me-2"></i>{{ type.type }}
                                </a>
                            {% empty %}
                                <p>No types found</p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="mb-5">
                        <h3 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                            Breeds
                        </h3>
                        <div class="d-flex flex-column justify-content-start">
                            {% for breed in breeds %}
                                <a class="h5 bg-light py-2 px-3 mb-2" href="?breed={{ breed.id }}">
                                    <i class="bi bi-arrow-right me-2"></i>{{ breed }}
                                </a>
                            {% empty %}
                                <p>
                                    No breeds found
                                </p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="mb-5">
                        <h3 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                            Sizes
                        </h3>
                        <div class="d-flex flex-column justify-content-start">
                            {% for size in sizes %}
                                <a class="h5 bg-light py-2 px-3 mb-2" href="?size={{ size.id }}">
                                    <i class="bi bi-arrow-right me-2"></i>{{ size }}
                                </a>
                            {% empty %}
                                <p>
                                    No sizes found
                                </p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="mb-5">
                        <h3 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                            Colors
                        </h3>
                        <div class="d-flex flex-column justify-content-start">
                            {% for color in colors %}
                                <a class="h5 bg-light py-2 px-3 mb-2" href="?color={{ color.id }}">
                                    <i class="bi bi-arrow-right me-2"></i>{{ color.color }}
                                </a>
                            {% empty %}
                                <p>
                                    No colors found
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="col-lg-9">
                    <div class="row g-4">
                        {% for pet in page_obj %}
                            <div class="col-lg-4">
                                <div class="team-item">
                                    <div class="position-relative overflow-hidden">
                                        <img class="img-fluid w-100" src="{{ pet.image.url }}" alt="">
                                    </div>
                                    <div class="bg-light text-center d-flex flex-column p-3">
                                        <a class="h5 bg-light" href="{% url 'pets:pet_detail' pk=pet.pk %}">
                                            {{ pet.name }}
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <p>
                                No pets found
                            </p>
                        {% endfor %}

                        {% if page_obj %}
                            <div class="col-12">
                                <nav aria-label="Page navigation">
                                    <ul class="pagination pagination-lg m-0">
                                        {% if page_obj.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link rounded-0" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                                    <span aria-hidden="true"><i class="bi bi-arrow-left"></i></span>
                                                </a>
                                            </li>
                                        {% endif %}
                                        <li class="page-item active">
                                            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                                        </li>
                                        {% if page_obj.has_next %}
                                            <li class="page-item">
                                                <a class="page-link rounded-0" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                                    <span aria-hidden="true"><i class="bi bi-arrow-right"></i></span>
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            </div>
                        {% else %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-light mt-4 py-5">
        <div class="container pt-2">
            <div class="row g5 justify-content-center">
                <div class="col-lg-4 offset-1">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Get In Touch
                    </h5>
                    <p class="mb-2">
                        <i class="bi bi-geo-alt text-primary me-2"></i>Our office: Tashkent, Uzbekistan
                    </p>
                    <p class="mb-2">
                        <i class="bi bi-envelope-open text-primary me-2"></i>Email Us: info@example.com
                    </p>
                    <p class="mb-0">
                        <i class="bi bi-telephone text-primary me-2"></i>Call Us: +998(99)123-45-67
                    </p>
                </div>
                <div class="col-lg-4 offset-2">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">
                        Quick Links
                    </h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Home
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>About Us
                        </a>
                        <a class="text-body mb-2" href="{% url 'pages:homepage' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Our Services
                        </a>
                        <a class="text-body mb-2" href="{% url 'posts:posts' %}">
                            <i class="bi bi-arrow-right text-primary me-2"></i>Blog
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-dark text-white-50 py-4">
        <div class="container">
            <div class="row g-5">
                <div class="text-center">
                    <p class="mb-0">
                        This template was designed by <a class="text-white" href="https://htmlcodex.com">HTML Codex</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <a href="#" class="btn btn-primary py-3 fs-4 back-to-top">
        <i class="bi bi-arrow-up"></i>
    </a>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>